Modify Competition Feature
nyx-ei/cjp pull request #52
Opened 2023-05-16 01:11 UTC by GT-Codeur

2023-05-16 02:11 UTC, SanAlexis approved these changes

2023-05-16 02:15 UTC, SanAlexis requested changes

2023-05-16 02:15 UTC, SanAlexis commented on modifyCompetitionInterface.html
> +        function displayCheckbox(){
Séparer le script du code html.

2023-05-16 02:16 UTC, SanAlexis requested changes
Très bonne approche. Il manque juste de séparer le code html des scripts pour faciliter la lecture, la maintenabilité et surtout réduire le couplage.

2023-05-16 02:20 UTC, GT-Codeur commented on modifyCompetitionInterface.html
> +        function displayCheckbox(){
Ok ça marche.

2023-06-30 17:05 UTC, SanAlexis approved these changes

2023-07-01 03:52 UTC, merged